### ISSUE TITLE
Do we want the 7 Habits?

### ISSUE THREAD

**Issue by jberkus** [vmbrasseur/10stepprogram#10]
V,

For GGTT, I usually performed "The 7 Habits of Highly Ineffective Speakers" in the middle of the tutorial, both for education and to break/wake things up.  Is that something we want to do/think about?

**Comment by vmbrasseur** [comment]
The content is good, but I feel it's already covered elsewhere (or can be) elsewhere in the presentation? Plus I think the exercises (plus lunch) will probably already break/wake things up.
