### ISSUE TITLE
Parcel out the sections

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/10stepprogram#12]
In advance of meeting up this weekend, let's markup the outline with our initials for the sections for which we're going to take responsibility for writing (not necessarily for presenting, though they may end up tracking).

My thinking is that this will allow us to do only the relevant research in advance of meeting up, rather than working on All The Things (and potentially duplicating effort).

**Comment by jberkus** [comment]
As a warning: realistically, I'm not going to have done any research.  I've been working 10 hours a day, and packing another 7 hours a day, for the last 11 days.  This doesnt' look likely to change until Dec. 21.

**Comment by vmbrasseur** [comment]
Oh, sure. And I'll probably be working a lot as well (though not NEARLY as much as you). If you claim what you think you can handle, I'll see what I can do about the rest.

**Comment by vmbrasseur** [comment]
Do this during #22

**Comment by vmbrasseur** [comment]
Closing in favor of #22
