### ISSUE TITLE
Do we want content for minority speakers?

### ISSUE THREAD

**Issue by jberkus** [vmbrasseur/10stepprogram#16]
This survey got me thinking, should we have specific stuff?  If so, what?  Not sure how to address, say, impostor syndrome.

https://t.co/ww0kfYalXA

**Comment by vmbrasseur** [comment]
I'm disinclined to have specific line items for this sort of stuff. We already have soooo much content. Instead, we can work it in by using inclusive examples and exercises?

**Comment by jberkus** [comment]
The only place I can think of is the audience interaction portion.  Like, male audience members will often be more obnoxious during Q&A to a female speaker.  No idea what do tell people to do about that though, except maybe be aggressive in cutting them off ...

**Comment by jberkus** [comment]
Closing
