### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/10stepprogram#34]
Spun off of #33 

Investigate the standard theming included with reveal.js.

**Comment by vmbrasseur** [comment]
Looking at the [themes which ship with reveal.js](https://github.com/hakimel/reveal.js/#theming). I'll **bold** the ones which I think are candidates.
- **black**: OK. Not thrilled but not offended.
- white: Way too stark. Not a fan.
- league: OMG no. There's this annoying target-like background.
- **beige**: OK but would have to lose the drop-shadow on the H1s
- **sky**: I like it but the H1 size needs to drop
- **night**: Ooh. I like this one rather a lot. My favorite so far.
- serif: Meh. Not doing a lot for me.
- **simple**: Pretty good, for a dark on light. I'd prefer it to be not quite so light, though.
- solarized: This is the default used by prez. It looks a bit too Americana for my taste.

**Comment by vmbrasseur** [comment]
## Black

OK. Not thrilled but not offended.

![screen shot 2016-01-17 at 21 12 31](https://cloud.githubusercontent.com/assets/298927/12383803/1bd54d68-bd5f-11e5-9f63-fcaf8b4f1083.png)

## Beige

OK but would have to lose the drop-shadow on the H1s

![screen shot 2016-01-17 at 21 14 12](https://cloud.githubusercontent.com/assets/298927/12383822/51f8721c-bd5f-11e5-87d5-8669cc1633dc.png)

## Sky

I like it but the H1 size needs to drop

![screen shot 2016-01-17 at 21 15 12](https://cloud.githubusercontent.com/assets/298927/12383836/72fbe7fa-bd5f-11e5-95b5-b49b468770bc.png)

## Night

Ooh. I like this one rather a lot. My favorite so far.

![screen shot 2016-01-17 at 21 16 07](https://cloud.githubusercontent.com/assets/298927/12383842/935fa8c4-bd5f-11e5-83d5-9e48a0c7470b.png)

## Simple

Pretty good, for a dark on light. I'd prefer it to be not quite so light, though.

![screen shot 2016-01-17 at 21 16 56](https://cloud.githubusercontent.com/assets/298927/12383853/b39f1dfe-bd5f-11e5-94ff-5d5e49835d7a.png)

**Comment by jberkus** [comment]
Night works for me.  Simple has too-thin characters; bad for visibility.  Not keen on anything with a gradated background.

So, Night?

**Comment by vmbrasseur** [comment]
Night it is.
