### ISSUE TITLE
Content ideas

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/10stepprogram#4]
For discussion:
- Name each section as though it were a Buzzfeed article (or an element of a "Top 10 Ways to…" Buzzfeed article)
- Use vintage ads or Weekly World News photos
- …?

**Comment by jberkus** [comment]
I think we should stick to the action-oriented titles.  Although "Fix your demo with this one wierd trick" has a certain temptation to it ...

**Comment by vmbrasseur** [comment]
$damian_conway;

But, yeah, I'm with ya. It was mostly just an idea I wanted to bounce. TBH, my problem with this approach is that to really make it work we'd have ot craft the entire presentation around the titles. We'd have to take on the faux personas of snake oil salesmen but without the snake oil. I think the approach could be as effective as it would be engaging/entertaining, but… `/me looks at her calendar for the next two months, informed-infers yours…` Uh, no.

**Comment by vmbrasseur** [comment]
I'm closing this for "WTF, vague much?"

Later we can open new issue(s) for better-defined questions.
