### ISSUE TITLE
Stuff to include

### ISSUE THREAD

**Issue by jberkus** [vmbrasseur/10stepprogram#5]
This issue is for a bunch of random stuff we need to add to the preso based on recent experience.
- [x] repeat the question: if someone asks a question in a large room, or you're being recorded, repeat it for the audience.
- [x] what if you have to cut your preso short because of time issues?
- [x] don't apologize for being a bad/inexperienced speaker.
- [x] Build in more time for questions

**Comment by jberkus** [comment]
More:
- don't apologize for being a bad/inexperienced speaker.

**Comment by vmbrasseur** [comment]
Updated to be checkboxes. Consolidated into a single list (the comment above is now a duplicate of what's in the description).

**Comment by vmbrasseur** [comment]
Moved some items here from the outline. Questions/comments about a couple of them:
- The eulogy thing isn't really sitting well with me for some reason. Are you attached to it?
- I don't recall at all what "Audience exercises -- advanced?" means. Can you remember?

**Comment by jberkus** [comment]
V,

Sadly, I don't recall what we meant my it either.

The eulogy quote is just a joke.  I works in the flow of other stuff we're presenting, or it doesn't.  Not attached to it.

**Comment by vmbrasseur** [comment]
I think these are more or less included in the outline now. Closing.
