### ISSUE TITLE
Select presentation software

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/10stepprogram#6]
## Criteria
- Cross-platform (read: works on Linux & OS X)
- Doesn't require a net connection
- Export to PDF (incl. speaker notes)
- ...?
## Nice-to-haves
- Text-based (easy diffs)
## Candidates to evaluate
- LibreOffice
- Google Docs
- [reveal.js](http://lab.hakim.se/reveal-js/#/)
- insert other options here

**Comment by jberkus** [comment]
Yeah, I think remark.js, as much as I love it, fails on several counts.  Probably reveal.js is the next-best; I don't like the markup, but it's way less painful than LO/GD.

**Comment by jberkus** [comment]
Note that the JS stuff can be run locally, you just need to run a local mini-webserver.

**Comment by vmbrasseur** [comment]
Wanna just try reveal.js, then?

**Comment by vmbrasseur** [comment]
Yup, we just agreed on IRC to use reveal.js.
