### ISSUE TITLE
Messaging around demos

### ISSUE THREAD

**Issue by jberkus** [vmbrasseur/10stepprogram#9]
I kinda feel like, for the past N years, both Damian and I have been overly negative about live demos.  This has resulted in speakers shying away from doing live demos even when doing so would be both good for the presentation, and relatively safe.

I would like to change the demo section to be more equivocal, like "here are the reasons to do a live demo, and here are the reasons to fake one."

**Comment by vmbrasseur** [comment]
That works for me. I feel that people should've been taught how to do demos properly (and when demos are effective and not) rather than being shunted away from them.

**Comment by vmbrasseur** [comment]
It looks like this is incorporated into the outline already. Closing the issue.
